name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build latest Docker image
      run: docker build . --file Dockerfile --tag unbound:latest
